[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "svelte-kit dev"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
