# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  branch: main

local_backend:
  url: http://localhost:8082/api/v1

media_folder: 'static/media'
public_folder: '/media'
media_folder_relative: false

collections: # A list of collections the CMS should be able to edit
  - name: content
    label: Content
    delete: false
    format: json
    files:
      - file: '/static/data/pages.json'
        label: Page List
        name: page
        editor:
          preview: false
        fields:
          - name: pages
            label: Pages
            label_singular: Page
            summary: 'Page {{fields.title}}'
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Enabled, name: enabled, widget: boolean, default: true }
              - { label: Page Slug, name: slug, widget: string }
              - { label: Teaser, name: teaser, widget: text }
              - { label: Keywords, name: keywords, widget: text, default: 'sveltekit, tailwindcss, netlify cms, typescript' }
              - { label: SEO, name: seo, widget: text }
              - { label: Body, name: body, widget: markdown }
              - label: Hero Image
                name: hero-image
                widget: image
                required: false
                media_library:
                  config:
                    multiple: true
